apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-admin-pvc
  namespace: jenkins-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi